# Generated by Django 3.1.2 on 2020-10-25 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_purchase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='datae',
            new_name='date',
        ),
    ]
